### ISSUE TITLE
已经开始收费了....

### ISSUE THREAD

**Issue by supine-win** [asundust/auth-captcha#1]

**Comment by asundust** [comment]
可以试试刚刚更新的版本 Vaptcha在轻量级业务下是免费的

**Comment by supine-win** [comment]
我之前试的时候都不给注册,

**Comment by asundust** [comment]
是的，我是很早申请内测的，号称免费。所以突然关闭内测的事情我也不知道是什么时候发生的，你在issue的时候那时候腾讯云还没开启正式收费，现在已经开启正式收费了。

**Comment by asundust** [comment]
**从2.0.0版本已经兼容多家验证码运营商**

**Comment by supine-win** [comment]
嗯
