### ISSUE TITLE
能否兼容下Dcat Admin？

### ISSUE THREAD

**Issue by izqx** [asundust/auth-captcha#8]
这个后台框架也是由laravel-admin二开的，界面还挺好看的。
如果能制作个Dcat Admin的扩展就更棒了

**Comment by asundust** [comment]
正在开发中 由于框架有点差异 这边另开一个扩展来开发 开发完成 会通知你的

**Comment by izqx** [comment]
> 正在开发中 由于框架有点差异 这边另开一个扩展来开发 开发完成 会通知你的

麻烦大佬了，我倒腾了半天才把谷歌的搞出来😂

**Comment by asundust** [comment]
你这边是 1.x 还是2.x版本？

**Comment by izqx** [comment]
> 你这边是 1.x 还是2.x版本？

用的是2.x的😀

**Comment by asundust** [comment]
由于前段时间比较忙 开发工作进展不顺 目前开发工作进行中 近日可上线

**Comment by asundust** [comment]
@izqx
现已开发完成

**Comment by izqx** [comment]
大佬牛逼~😀

**Comment by asundust** [comment]
包相关地址移步
https://github.com/asundust/dcat-auth-captcha/
https://packagist.org/packages/asundust/dcat-auth-captcha
composer require asundust/dcat-auth-captcha
